spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/social_media_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
