spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"
  servlet:
    multipart:
      max-file-size: 10MB

file:
  directory: files

socialmedia:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://mydomen.com

springdoc:
  swagger-ui:
    tryItOutEnabled: true

